--- 
title: "Libro Personal de Apuntes"
author: "Hecho por Esteban Rucán Carrasco"
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
fontsize: 10pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
site: bookdown::bookdown_site
description: "Expande tus conocimientos de R con el material que he preparado."
github-repo: estebanrucan/personal-book
graphics: yes
params:
  especie: "setosa"
---

```{r setup, include=FALSE, eval=TRUE}
library(knitr)

opts_chunk$set( 
  comment = "",
  fig.align = "center", 
  tidy = FALSE, 
  tidy.opts = list(width.cutoff = 10)
)

options(
  htmltools.dir.version = FALSE, 
  formatR.indent = 2, 
  width = 55, 
  digits = 4,
  dplyr.summarise.inform = FALSE
)

if(is_latex_output()){
  opts_chunk$set(
    out.width = "\\textwidth", 
    fig.width = 8, 
    fig.asp = 0.618,
    fig.pos = "H"
  )
}

pkgs <- c('magrittr', 
          'knitr', 
          'echarts4r',
          'BiocManager',
          'gt',
          'tidyverse')

pacman::p_load(pkgs, character.only = TRUE)

# otherwise output in PDF blurry

write_bib(c(.packages(), pkgs), 'packages.bib')

# fix remotes bib
bib <- readLines("packages.bib")
bib <- gsub("#readme", "", bib)
writeLines(bib, "packages.bib")
```

# Prefacio {-}

Hola, mi nombre es Esteban Rucán, actual estudiante de cuarto año de la carrera de Estadística en la [Pontificia Universidad Católica de Chile](https://www.uc.cl). 

Agradezco que hayas ingresado a mi libro personal. En él encontrarás apuntes de diversos temas que he realizado con mucha dedicación, con el fin de poder contribuir a quien lo necesite. Si este es tu caso, espero que disfrutes el material disponible. ¡Si tienes alguna sugerencia o duda no dudes en escribirme a mi [correo](mailto:errucan@uc.cl)!.

Puedes difundir la información de este libro siempre y cuando me lo informes.

## Estructura del libro

El libro contiene apuntes enfocados principalmente en el lenguaje `R`, por lo que la mayoría de su contenido esta enfocado en este. Podrás navegar entre diversos tópicos sobre el lenguaje desde la barra lateral. También está habilitado un modo oscuro y un selector de fuente en la parte superior de tu pantalla.

## Agradecimientos

Sin duda, todos los conocimietos que tengo de `R` se los debo a los docentes que me han realizado clases, en conjunto a muchas plataformas para practicar el software. Si te identifica esta frase, te quiero dar mis sinceras gratitudes.

En la próxima página encontrarás algunas páginas y libros interesantes, todo libre de *Copyright*.
